### ISSUE TITLE
Update of 1.0.37RC to 1.1.0RC failed

### ISSUE THREAD

**Issue by waran70** [YetiForceCompany/UpdatePackages#3]
The result of update is:
- Adding Account or Contact returning error
- update procedure doubling submenu "Updates" under Menu "About Yetiforce" in the settings.

**Comment by bpabiszczak** [comment]
a czemu tu nie ma żadnego komentarza jest tylko zamknięcie? 
---

Z poważaniem / Regards 

BŁAŻEJ PABISZCZAK 
_Chief Executive Officer_ 
M: +48.884999123
E: b.pabiszczak@yetiforce.com 
-------------------------

We created an innovative CRM system that is open and adapts perfectly to
your business. Find out about its capabilities by downloading it [3] or
testing [4]. Change your system to YetiForce [5]! 

W dniu 2015-01-21 10:17, Mariusz Krzaczkowski napisał(a): 

> Closed #3 [1]. 
> 
> --
> Reply to this email directly or view it on GitHub [2].
 

Links:
------
[1] https://github.com/YetiForceCompany/UpdatePackages/issues/3
[2]
https://github.com/YetiForceCompany/UpdatePackages/issues/3#event-222177448
[3] https://sourceforge.net/projects/yetiforce/
[4] https://test.yetiforce.com
[5] https://yetiforce.com/
